name: Checks
on:
    pull_request:
        types: [opened, synchronize]

jobs:
    checks:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: "Use NodeJS 20"
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: "Setup npm"
              run: |
                  npm set @ponderingdemocritus:registry=https://npm.pkg.github.com/dojoengine
                  npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

            - name: Install dependencies
              run: |
                  pnpm i
                  pnpm build
                  pnpm build-examples

            - name: Run tests
              run: pnpm test
