name: Prepare Release

on:
    workflow_call:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
            - uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: Configure Git
              run: |
                  git config user.name "${{ github.actor }}"
                  git config user.email "${{ github.actor}}@users.noreply.github.com"

            - name: "Setup npm"
              run: |
                  npm set @ponderingdemocritus:registry=https://npm.pkg.github.com/dojoengine
                  npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

            - name: Install Protobuf Compiler
              run: sudo apt-get install -y protobuf-compiler

            - name: Install dependencies
              run: pnpm i

            - name: Build dependencies
              run: pnpm run build
